"""Refusal / parse-failure rate across the reasoning-effort x temperature
grid, all three datasets, sourced from prediction/llm_pred/metric/llm_batch_quality.csv
(built by llm_uq_batch_quality.py from each corpus's text_predictions_*.csv
and batch_errors_*.jsonl). "Failure" here means one of:

  1. Null response          -- the completion text itself is empty.
  2. Refuses to answer      -- explicit refusal language ("I can't assess...",
                                "unable to determine", "as an AI") AND no
                                q_hat was produced. A refusal PHRASE that
                                still yields a q_hat is hedging inside the
                                reasoning, not a refusal -- shown as a
                                separate, explicitly-not-a-failure row for
                                transparency, not folded into the count.
  3. Fails to parse          -- EVERY prompted field (extraction fields plus
     important info            q_hat/verdict) came back null on the same
                                row. A single null field is usually the
                                source paper not reporting that value (most
                                visible in CB, where ~92/158 effects have
                                no effect size that converts to r at all --
                                see llm_batch_quality.csv's per-field null
                                columns for that breakdown); an ALL-null row
                                cannot be explained that way.

Excludes credit_balance_exhausted (8392 requests: 6966 CB + 863 RPP high/0.7
+ 563 RPP high/0.2) -- billing rejections the API returned before the model
ever saw the request, not anything the model did. Also excludes one further RPP API-level rejection whose error
code was not captured (batch_errors.jsonl, untagged submission) -- reported
separately in the caption rather than silently merged into either the
credit-balance count or the failure count, since its cause is unknown.

Usage: rep_env/bin/python tables/llm_uq_table_refusal_grid.py
Writes: tables/table6_refusal_grid.tex
"""
import os

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUALITY_CSV = os.path.join(REPO, "prediction", "llm_pred", "metric", "llm_batch_quality.csv")
API_ERR_CSV = os.path.join(REPO, "prediction", "llm_pred", "metric", "llm_batch_api_errors.csv")
OUT_TEX = os.path.join(REPO, "tables", "table6_refusal_grid.tex")

CORPORA = ["RPP", "CB", "SSRP"]
GRID_CELLS = [("high", "0.7"), ("low", "0.7"), ("high", "0.2"), ("low", "0.2")]

METRICS = [
    (r"Null response", "empty_completion", True),
    (r"Refuses to answer", "refusal_phrase_no_answer", True),
    (r"Fails to parse (all fields null)", "none_fields_parsed", True),
    (r"\quad(hedging language, still answered)", "refusal_phrase", False),
]


def cell_row(df, corpus, effort, temp):
    return df[(df.corpus == corpus) & (df.effort == effort) & (df.temp == float(temp))].iloc[0]


def main():
    df = pd.read_csv(QUALITY_CSV)
    err = pd.read_csv(API_ERR_CSV)

    credit = int(err.loc[err.code == "credit_balance_exhausted", "count"].sum())
    other = err[err.code != "credit_balance_exhausted"]
    other_n = int(other["count"].sum())

    tex = [
        r"% Generated by llm_uq_table_refusal_grid.py -- do not edit by hand.",
        r"\begin{table}[h]", r"\centering",
        r"\caption{Refusal and parse-failure counts across the reasoning-effort "
        r"$\times$ temperature grid, $R{=}100$ per cell, all three corpora "
        rf"(collected $n$: RPP {int(cell_row(df, 'RPP', 'high', '0.7').collected)}, "
        rf"CB {int(cell_row(df, 'CB', 'high', '0.7').collected)}, "
        rf"SSRP {int(cell_row(df, 'SSRP', 'high', '0.7').collected)} per cell). "
        r"``Refuses to answer'' requires explicit refusal language AND no "
        r"\texttt{q\_hat} produced; a refusal phrase that still yields an answer "
        r"is hedging, shown separately and not counted as a failure. "
        r"``Fails to parse'' requires every prompted field null on the same row "
        r"-- a single null field is usually the source paper not reporting that "
        rf"value, not a model failure (see llm\_batch\_quality.csv). Excludes "
        rf"{credit} requests rejected by the API for insufficient account credit "
        rf"before the model saw them (not a model failure), plus {other_n} further "
        r"API-level rejection of unrecorded cause.}",
        r"\label{tab:refusal-grid}", r"\small",
        r"\begin{tabular}{@{}ll cc cc@{}}", r"\toprule",
        r" & & \multicolumn{2}{c}{Temperature 0.7} & \multicolumn{2}{c}{Temperature 0.2} \\",
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}",
        r"\textbf{Corpus} & \textbf{Failure type} & \textbf{high effort} & "
        r"\textbf{low effort} & \textbf{high effort} & \textbf{low effort} \\",
        r"\midrule",
    ]
    for i, corpus in enumerate(CORPORA):
        if i:
            tex.append(r"\midrule")
        for j, (label, col, is_failure) in enumerate(METRICS):
            lead = corpus if j == 0 else ""
            vals = [str(int(cell_row(df, corpus, eff, t)[col])) for eff, t in GRID_CELLS]
            tex.append(f"{lead} & {label} & " + " & ".join(vals) + r" \\")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(tex) + "\n")

    for corpus in CORPORA:
        for eff, t in GRID_CELLS:
            r = cell_row(df, corpus, eff, t)
            print(f"{corpus:6s} {eff:4s}/{t}: null={r.empty_completion} "
                  f"refuse={r.refusal_phrase_no_answer} "
                  f"parse-fail={r.none_fields_parsed} "
                  f"(hedge, still answered={r.refusal_phrase})")
    print(f"\nExcluded: {credit} credit_balance_exhausted + {other_n} other API-level "
          f"rejection(s), not counted as failures.")
    print(f"Wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
