"""Two paper artifacts, both read from llm_uq/prediction/llm_pred/metric/llm_uq_grid_summary.csv
(itself built by llm_uq_grid_summary.py from the per-cell metric CSVs) so
neither can carry a stale number without the source CSV also being stale:

  1. Table 4 -- the full 3-corpus x 2-effort x 2-temp AUC grid (Hanley-McNeil
     SE), all 12 cells. The draft version of this table already had RPP and
     CB temp=0.7 filled in, but from an earlier vintage of the R=100
     runs -- this script's own values differ from those (see the printed
     diff against DRAFT_TABLE4 below), not just from filling in the blank
     temp=0.2 columns for CB/SSRP the draft explicitly deferred.

  2. Table 5 -- the same calibration/dispersion metrics as a full effort x
     temperature grid (same 4-column layout as Table 4) instead of just the
     canonical cell. AUC(agreement -> correct) is recomputed per cell here,
     not reused from the canonical cell alone -- each of the 12
     llm_selfconsistency*_dispersion.csv files supports it.

This script originally also wrote a canonical-cell-only calibration
paragraph (ECE / dispersion / entropy / agreement prose); that paragraph is
no longer used in the paper (Table 5 covers the same numbers) and has been
archived to archive/paper_writeups/calibration_paragraph.py.

Usage: rep_env/bin/python llm_uq/tables/llm_uq_table_grid_calibration.py
Writes: llm_uq/tables/table4_grid.tex
        llm_uq/tables/table5_calibration_grid.tex
"""
import os

import pandas as pd
from sklearn.metrics import roc_auc_score

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRID_CSV = os.path.join(REPO, "prediction", "llm_pred", "metric", "llm_uq_grid_summary.csv")
OUT_TABLE4 = os.path.join(REPO, "tables", "table4_grid.tex")
OUT_TABLE5 = os.path.join(REPO, "tables", "table5_calibration_grid.tex")

DISP_SLUG = {("high", "0.7"): "", ("low", "0.7"): "_low",
            ("high", "0.2"): "_temp0.2", ("low", "0.2"): "_low_temp0.2"}
CORPUS_DISP_INFIX = {"RPP": "", "CB": "_cb_full", "SSRP": "_ssrp"}
GRID_CELLS = [("high", "0.7"), ("low", "0.7"), ("high", "0.2"), ("low", "0.2")]

CORPORA = ["RPP", "CB", "SSRP"]
CORPUS_ROW_LABEL = {"RPP": "RPP", "CB": "CB", "SSRP": "SSRP"}

# What the draft's Table 4 already showed for temp=0.7 (AUC, SD), transcribed
# from the submitted image -- kept here only so main() can print a diff
# against this script's numbers and flag any cell that moved, not just the
# ones that were previously blank.
DRAFT_TABLE4 = {
    ("RPP", "vbar", "high", "0.7"): (0.704, 0.060), ("RPP", "vbar", "low", "0.7"): (0.656, 0.062),
    ("RPP", "qbar", "high", "0.7"): (0.659, 0.062), ("RPP", "qbar", "low", "0.7"): (0.631, 0.063),
    ("CB", "vbar", "high", "0.7"): (0.709, 0.042), ("CB", "vbar", "low", "0.7"): (0.656, 0.044),
    ("CB", "qbar", "high", "0.7"): (0.694, 0.043), ("CB", "qbar", "low", "0.7"): (0.601, 0.046),
    ("SSRP", "vbar", "high", "0.7"): (0.827, 0.090), ("SSRP", "vbar", "low", "0.7"): (0.870, 0.078),
    ("SSRP", "qbar", "high", "0.7"): (0.788, 0.100), ("SSRP", "qbar", "low", "0.7"): (0.856, 0.083),
}


def cell(df, corpus, predictor, effort, temp):
    r = df[(df.corpus == corpus) & (df.effort == effort) & (df.temp == float(temp))].iloc[0]
    return r[f"AUC_{predictor}"], r[f"AUC_{predictor}_SD"]


def fmt(auc, sd):
    return rf"{auc:.3f} $\pm$ {sd:.3f}"


def build_table4(df):
    tex = [
        r"% Generated by llm_uq_table_grid_calibration.py -- do not edit by hand.",
        r"\begin{table}[h]", r"\centering",
        r"\caption{Reasoning-effort $\times$ temperature grid, AUC (Hanley--McNeil SE), "
        r"$R{=}100$ per cell, all three corpora and both temperatures. "
        r"SSRP's reversal of the effort ordering (low effort scores higher than high) "
        r"holds at both temperatures and occurs within wide SEs at $n{=}21$; not interpreted.}",
        r"\label{tab:effort-temp-grid}", r"\small",
        r"\begin{tabular}{@{}ll cc cc@{}}", r"\toprule",
        r" & & \multicolumn{2}{c}{Temperature 0.7} & \multicolumn{2}{c}{Temperature 0.2} \\",
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}",
        r"\textbf{Corpus} & \textbf{Predictor} & \textbf{high effort} & \textbf{low effort} "
        r"& \textbf{high effort} & \textbf{low effort} \\",
        r"\midrule",
    ]
    for i, corpus in enumerate(CORPORA):
        if i:
            tex.append(r"\midrule")
        for j, (pred, sym) in enumerate([("vbar", r"$\bar v$"), ("qbar", r"$\bar q$")]):
            lead = rf"{CORPUS_ROW_LABEL[corpus]}" if j == 0 else ""
            row = [fmt(*cell(df, corpus, pred, eff, t))
                   for eff, t in [("high", "0.7"), ("low", "0.7"), ("high", "0.2"), ("low", "0.2")]]
            tex.append(f"{lead} & {sym} & " + " & ".join(row) + r" \\")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(tex) + "\n"


def print_draft_diff(df):
    print("Diff against the draft's existing temp=0.7 cells (draft -> this script):")
    changed = 0
    for (corpus, pred, effort, temp), (d_auc, d_sd) in DRAFT_TABLE4.items():
        auc, sd = cell(df, corpus, pred, effort, temp)
        moved = abs(auc - d_auc) >= 0.001 or abs(sd - d_sd) >= 0.001
        flag = "  <-- CHANGED" if moved else ""
        changed += moved
        print(f"  {corpus:6s} {pred:4s} {effort:4s}/{temp}: "
              f"{d_auc:.3f}±{d_sd:.3f} -> {auc:.3f}±{sd:.3f}{flag}")
    print(f"{changed}/{len(DRAFT_TABLE4)} previously-filled cells moved by >=0.001.\n")


def auc_agree_per_cell():
    """{(corpus, effort, temp): AUC(pairwise_agreement -> correct)}, one per
    cell, from that cell's own llm_selfconsistency*_dispersion.csv -- not
    reused from the canonical cell, since dispersion (and what it predicts)
    is exactly the thing this table is checking across the grid."""
    out = {}
    for corpus, infix in CORPUS_DISP_INFIX.items():
        for effort, temp in GRID_CELLS:
            path = os.path.join(REPO, "prediction", "llm_pred", "metric",
                                f"llm_selfconsistency{infix}{DISP_SLUG[(effort, temp)]}_dispersion.csv")
            d = pd.read_csv(path)
            out[(corpus, effort, temp)] = roc_auc_score(d["correct"], d["pairwise_agreement"])
    return out


def build_table5(df):
    auc_agree = auc_agree_per_cell()

    def row_vals(corpus, colfn):
        return [colfn(df[(df.corpus == corpus) & (df.effort == eff)
                         & (df.temp == float(t))].iloc[0], corpus, eff, t)
                for eff, t in GRID_CELLS]

    metrics = [
        (r"ECE($\bar q$)", lambda r, c, e, t: f"{r.ECE_qbar:.3f}"),
        (r"SD($\hat q$)", lambda r, c, e, t: f"{r.q_sd_mean:.3f}"),
        (r"ECE($\bar v$)", lambda r, c, e, t: f"{r.ECE_vbar:.3f}"),
        (r"Entropy($\bar v$), bits", lambda r, c, e, t: f"{r.verdict_entropy_bits_mean:.3f}"),
        (r"Agreement($\bar v$)", lambda r, c, e, t: f"{r.pairwise_agreement_mean:.3f}"),
        (r"AUC(agreement $\to$ correct)",
         lambda r, c, e, t: f"{auc_agree[(c, e, t)]:.3f}"),
    ]

    tex = [
        r"% Generated by llm_uq_table_grid_calibration.py -- do not edit by hand.",
        r"\begin{table}[h]", r"\centering",
        r"\caption{Calibration and dispersion metrics across the reasoning-effort "
        r"$\times$ temperature grid, $R{=}100$ per cell, all three corpora. "
        r"ECE is from fixed-size quantile bins (5 for RPP/CB; 3 for SSRP), with "
        r"tied scores ordered by the recorded NumPy quicksort convention. The first five rows are "
        r"label-free (SD($\hat q$), entropy, and pairwise agreement need no ground "
        r"truth to compute); the last row, AUC(agreement $\to$ correct), is the one "
        r"row that does -- it scores whether a claim's pairwise run-to-run agreement "
        r"(how often two of its $R{=}100$ runs agree on the verdict) predicts whether "
        r"the AGGREGATED verdict for that claim was actually correct, treating "
        r"agreement as a classifier and correctness as the label (0.5 = chance, matching "
        r"SelfCheckGPT-style validation of self-consistency as an uncertainty signal). "
        r"Every value supersedes the $R{=}25$ pilot previously reported for RPP; CB "
        r"and SSRP were not previously reported.}",
        r"\label{tab:calibration-grid}", r"\small",
        r"\begin{tabular}{@{}ll cc cc@{}}", r"\toprule",
        r" & & \multicolumn{2}{c}{Temperature 0.7} & \multicolumn{2}{c}{Temperature 0.2} \\",
        r"\cmidrule(lr){3-4} \cmidrule(lr){5-6}",
        r"\textbf{Corpus} & \textbf{Metric} & \textbf{high effort} & \textbf{low effort} "
        r"& \textbf{high effort} & \textbf{low effort} \\",
        r"\midrule",
    ]
    for i, corpus in enumerate(CORPORA):
        if i:
            tex.append(r"\midrule")
        for j, (label, colfn) in enumerate(metrics):
            lead = CORPUS_ROW_LABEL[corpus] if j == 0 else ""
            vals = row_vals(corpus, colfn)
            tex.append(f"{lead} & {label} & " + " & ".join(vals) + r" \\")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(tex) + "\n"


def main():
    df = pd.read_csv(GRID_CSV)
    print_draft_diff(df)

    table4 = build_table4(df)
    with open(OUT_TABLE4, "w", encoding="utf-8") as f:
        f.write(table4)
    print(f"Wrote {OUT_TABLE4}")

    table5 = build_table5(df)
    with open(OUT_TABLE5, "w", encoding="utf-8") as f:
        f.write(table5)
    print(f"Wrote {OUT_TABLE5}")


if __name__ == "__main__":
    main()
