"""SSRP reasoning-effort comparison: high vs low, same two label-free
elicitation methods (verbalized confidence q-bar, self-consistency vote
rate v-bar) as table_llm_uq_cross_corpus.tex (llm_uq_table.py --table cross_corpus),
but rows are effort variants of the SAME corpus instead of different
datasets. Reuses llm_uq_table.py's load_corpus(), so "_ssrp_low"
(predict_llm_uq.py/predict_llm_verdict.py --dataset ssrp with
REASONING_EFFORT=low) loads exactly like "_ssrp" (high).

High effort is the canonical config (temp=0.7, R=100); this table
characterizes the effort tradeoff.

Reads:
    prediction/llm_pred/metric/llm_qbar_ssrp_metrics.csv, llm_verdict_ssrp_metrics.csv,
        llm_calibration_ssrp.csv, llm_selfconsistency_ssrp_dispersion.csv
    prediction/llm_pred/metric/llm_qbar_ssrp_low_metrics.csv, llm_verdict_ssrp_low_metrics.csv,
        llm_calibration_ssrp_low.csv, llm_selfconsistency_ssrp_low_dispersion.csv

Usage: rep_env/bin/python tables/llm_uq_table_ssrp_effort_comparison.py
Writes: tables/table_ssrp_effort_comparison.tex
"""
import os

import pandas as pd

try:
    from .llm_uq_table import load_corpus
except ImportError:  # direct execution from the repository root
    from llm_uq_table import load_corpus

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_NAME = "gpt-5.4-mini"

SSRP_HIGH = {
    "key": "SSRP", "slug": "_ssrp", "unit": "studies",
    "pred": os.path.join(REPO, "prediction", "LLM_Reasoning", "SSRP", "text_predictions_high_temp0.7.csv"),
}
SSRP_LOW = {
    "key": "SSRP-low", "slug": "_ssrp_low", "unit": "studies",
    "pred": os.path.join(REPO, "prediction", "LLM_Reasoning", "SSRP", "text_predictions_low_temp0.7.csv"),
}


def main():
    high = load_corpus(SSRP_HIGH)
    low = load_corpus(SSRP_LOW)
    n_high, r_high, rows_high = high["n"], high["R"], high["rows"]
    n_low, r_low, rows_low = low["n"], low["R"], low["rows"]
    assert n_high == n_low, "high/low must score the same 21 studies"

    print(f"SSRP high effort (n={n_high}, R={r_high})")
    print(pd.DataFrame(rows_high).to_string(index=False))
    print(f"\nSSRP low effort (n={n_low}, R={r_low})")
    print(pd.DataFrame(rows_low).to_string(index=False))

    tex = [
        r"% Generated by llm_uq_table_ssrp_effort_comparison.py -- do not edit by hand.",
        r"\begin{table}[h]", r"\centering",
        rf"\caption{{SSRP reasoning-effort tradeoff for {MODEL_NAME}: the same "
        rf"two label-free elicitation methods as table\_llm\_uq\_cross\_corpus.tex "
        rf"(verbalized confidence $\bar q$, self-consistency vote rate $\bar v$), "
        rf"scored on the same {n_high} SSRP studies at $R{{=}}{r_high}$ zero-shot "
        rf"runs per study, reasoning\_effort=high vs.\ low (temp=0.7 both). AUC "
        rf"$\pm$ Hanley\textendash McNeil (1982) SE; Accuracy $\pm$ Wald binomial "
        rf"SE; ECE from 3 quantile-binned reliability bins. High is this "
        rf"project's canonical config; low is shown only as a cost/quality "
        rf"reference point, not used anywhere else downstream.}}",
        r"\label{tab:ssrp-effort-comparison}", r"\small",
        r"\begin{tabular}{@{}ll cc c c@{}}", r"\toprule",
        r" & & \multicolumn{3}{c}{vs.\ ground truth} & \multicolumn{1}{c}{label-free} \\",
        r"\cmidrule(lr){3-5} \cmidrule(lr){6-6}",
        r"\textbf{Effort} & \textbf{Elicitation method} & \textbf{AUC} & \textbf{Accuracy} & "
        r"\textbf{ECE} & \textbf{Run-to-run dispersion} \\", r"\midrule",
    ]
    for effort_label, rows in [(r"High", rows_high), (r"Low", rows_low)]:
        for i, r_ in enumerate(rows):
            effort_cell = effort_label if i == 0 else ""
            tex.append(f"{effort_cell} & {r_['method']} & {r_['AUC']} & {r_['Accuracy']} & "
                        f"{r_['ECE']} & {r_['dispersion']} \\\\")
        if effort_label != "Low":
            tex.append(r"\addlinespace")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    out_tex = os.path.join(REPO, "tables", "table_ssrp_effort_comparison.tex")
    os.makedirs(os.path.dirname(out_tex), exist_ok=True)
    with open(out_tex, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"\nWrote {out_tex}")


if __name__ == "__main__":
    main()
