"""Two-row-per-corpus embed_pred comparison table, styled like
tables/table_predictor_comparison.tex (bare Predictor/Evaluation/AUC/
Accuracy, no Brier/ECE/dispersion) -- NOT the SD/ECE/dispersion table
make_classification_tables.py builds, and not a zero-shot-LLM table either
(no gpt-5.4-mini q-bar/v-bar rows; those are in table_llm_uq_cross_corpus.tex).

Each corpus gets two rows, because "the AUC" of a 20-seed repeated nested CV
is ambiguous between two different quantities that can disagree a lot at
small n:

  per-seed mean    mean and SD of the 20 individual per-seed AUC/Accuracy
                   values -- what a single nested-CV run would actually look
                   like, and how much it swings run to run.
  mean probability AUC/Accuracy of the per-effect/per-study AVERAGE
                   out-of-fold probability across the 20 seeds, with the
                   closed-form Hanley-McNeil (1982)/Wald SD of that single
                   point estimate. Averaging probabilities before scoring is
                   a real variance-reduction step (not leakage -- every
                   seed's prediction for a sample still comes from a model
                   that never saw that sample), but it describes a 20-way
                   ensemble, not a single run, so it reads more optimistic.

At SSRP's n=21 the two disagree by more than the per-seed SD (0.661 vs.
0.846 AUC) -- exactly the case where reporting only the mean-probability row
would overstate what a single run finds. At CB's n=158 the two nearly agree
(0.547 vs. 0.581), because more data means less to gain from averaging out
fold-assignment noise. Both rows are kept side by side rather than picking
one, so the gap itself is visible instead of hidden.

Reads:
    prediction/embed_pred/CB/embed_lr_metrics.csv
    prediction/embed_pred/SSRP/embed_lr_metrics.csv

Usage: rep_env/bin/python tables/table_predictor_comparison_cross_corpus.py
Writes: tables/table_predictor_comparison_cross_corpus.tex
"""
import os

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CB_METRICS_CSV = os.path.join(REPO, "prediction", "embed_pred", "CB", "embed_lr_metrics.csv")
SSRP_METRICS_CSV = os.path.join(REPO, "prediction", "embed_pred", "SSRP", "embed_lr_metrics.csv")
OUT_TEX = os.path.join(REPO, "tables", "table_predictor_comparison_cross_corpus.tex")

N_SEEDS = 20


def cv_rows(metrics_csv):
    """-> (mean-probability row w/ Hanley-McNeil/Wald SD,
           per-seed-mean row, per-seed-SD row)"""
    metrics = pd.read_csv(metrics_csv)
    avg = metrics[metrics["evaluation"].str.contains(f"{N_SEEDS}-seed avg")].iloc[0]
    mean = metrics[metrics["evaluation"].str.contains(f"per-seed \\(mean of {N_SEEDS}\\)")].iloc[0]
    sd = metrics[metrics["evaluation"].str.contains(f"per-seed \\(sd of {N_SEEDS}\\)")].iloc[0]
    return avg, mean, sd


def main():
    cb_avg, cb_mean, cb_sd = cv_rows(CB_METRICS_CSV)
    ssrp_avg, ssrp_mean, ssrp_sd = cv_rows(SSRP_METRICS_CSV)

    rows = []
    for label, avg, mean, sd in [
        (r"CB (effect level)", cb_avg, cb_mean, cb_sd),
        (r"SSRP (study level)", ssrp_avg, ssrp_mean, ssrp_sd),
    ]:
        rows.append({
            "corpus": label, "n": int(avg.n), "evaluation": rf"per-seed mean ($N{{=}}{N_SEEDS}$)",
            "AUC": mean.AUC, "AUC_sd": sd.AUC, "Accuracy": mean.Accuracy, "Accuracy_sd": sd.Accuracy,
        })
        rows.append({
            "corpus": label, "n": int(avg.n), "evaluation": r"mean probability",
            "AUC": avg.AUC, "AUC_sd": avg.AUC_SD, "Accuracy": avg.Accuracy, "Accuracy_sd": avg.Accuracy_SD,
        })

    df = pd.DataFrame(rows)
    print(df.to_string(index=False))

    tex = [
        r"% Generated by table_predictor_comparison_cross_corpus.py -- do not edit by hand.",
        r"\begin{table}[h]", r"\centering",
        rf"\caption{{Text-embedding Lasso LR replication-prediction performance on "
        rf"CB's {int(cb_avg.n)} completed effects and SSRP's {int(ssrp_avg.n)} "
        rf"studies, from repeated nested CV ($N{{=}}{N_SEEDS}$ independent outer/inner "
        rf"StratifiedKFold splits). \emph{{Per-seed mean}} is the mean and SD of the "
        rf"{N_SEEDS} individual per-seed AUC/Accuracy values -- what a single run of "
        rf"this pipeline would actually look like. \emph{{Mean probability}} is the "
        rf"AUC/Accuracy of the per-effect/per-study average out-of-fold probability "
        rf"across the {N_SEEDS} seeds, $\pm$ the closed-form Hanley\textendash McNeil "
        rf"(1982)/Wald SD of that single point estimate -- a real but different "
        rf"quantity (a {N_SEEDS}-way ensemble), which is why it can read higher than "
        rf"the per-seed mean, especially at SSRP's small $n$. Accuracy thresholds at "
        rf"0.5.}}",
        r"\label{tab:predictor-comparison-cb-ssrp}", r"\small",
        r"\begin{tabular}{@{}llrr@{}}", r"\toprule",
        r"\textbf{Corpus} & \textbf{Evaluation} & \textbf{AUC} & \textbf{Accuracy} \\", r"\midrule",
    ]
    prev_corpus = None
    for r_ in rows:
        corpus_cell = r_["corpus"] if r_["corpus"] != prev_corpus else ""
        tex.append(f"{corpus_cell} & {r_['evaluation']} & "
                    f"{r_['AUC']:.3f} $\\pm$ {r_['AUC_sd']:.3f} & "
                    f"{r_['Accuracy']:.3f} $\\pm$ {r_['Accuracy_sd']:.3f} \\\\")
        prev_corpus = r_["corpus"]
        if r_["evaluation"] == "mean probability" and r_ is not rows[-1]:
            tex.append(r"\addlinespace")
    tex += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]

    os.makedirs(os.path.dirname(OUT_TEX), exist_ok=True)
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(tex) + "\n")
    print(f"\nWrote {OUT_TEX}")


if __name__ == "__main__":
    main()
