"""Step 14 (dml_spec.md): LaTeX table + figures built from dml_theta.csv.

Usage: rep_env/bin/python uq_bound/dml/dml_theta_outputs.py
Writes: uq_bound/dml/table_dml_theta.tex
        uq_bound/figures/dml_theta_attribution_cluster_robust.pdf/.png
        uq_bound/figures/dml_theta_attribution_bootstrap.pdf/.png
"""
import os

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

HERE = os.path.dirname(os.path.abspath(__file__))
DOC_DIR = HERE
FIG_DIR = os.path.join(HERE, "figures")
STAGE_ORDER = ["theta_1 (Extraction)", "theta_2 (Stat review)", "theta_3 (Researcher DoF)",
               "theta_4 (Theory/context)", "theta_res (Residual)"]
SHORT = {"theta_1 (Extraction)": r"$\theta_1$ Extraction",
         "theta_2 (Stat review)": r"$\theta_2$ Stat review",
         "theta_3 (Researcher DoF)": r"$\theta_3$ Researcher DoF",
         "theta_4 (Theory/context)": r"$\theta_4$ Theory/context",
         "theta_res (Residual)": r"$\theta_{\text{res}}$ Residual"}


def build_table(d):
    """Two intervals per the request: cluster-robust (normal) and the
    study-cluster bootstrap interval from the same multiplier-bootstrap
    draws as the Step 10 simultaneous band -- applied identically to all
    three corpora, no small-G variant."""
    lines = [
        r"% Generated by dml_theta_outputs.py -- do not edit by hand.",
        r"\begin{tabular}{llrrrr}",
        r"\toprule",
        r"Corpus & Stage & $\hat\theta_m$ & Share & 95\% CI (cluster-robust) & 95\% CI (bootstrap) \\",
        r"\midrule",
    ]
    for corpus in ["RPP", "CB", "SSRP"]:
        sub = d[d.corpus == corpus].set_index("stage").loc[STAGE_ORDER]
        for i, (stage, row) in enumerate(sub.iterrows()):
            cname = corpus if i == 0 else ""
            lines.append(
                f"{cname} & {SHORT[stage]} & {row['theta_hat']:.5f} & "
                f"{100*row['share_of_total']:.1f}\\% & "
                f"[{row['ci95_lo_normal']:.5f}, {row['ci95_hi_normal']:.5f}] & "
                f"[{row['ci95_lo_boot']:.5f}, {row['ci95_hi_boot']:.5f}] \\\\"
            )
        lines.append(r"\addlinespace")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines)


def build_figure(d, lo_col, hi_col, interval_title):
    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    corpora = ["RPP", "CB", "SSRP"]
    labels = {"RPP": "RPP (n=90, G=88)",
              "CB": "CB (n=103/158, G=20)",
              "SSRP": "SSRP (n=21, G=21)"}
    colors = {"RPP": "#0072B2", "CB": "#D55E00", "SSRP": "#009E73"}
    markers = {"RPP": "o", "CB": "s", "SSRP": "D"}
    offsets = {"RPP": -0.18, "CB": 0.0, "SSRP": 0.18}
    x = np.arange(len(STAGE_ORDER))

    for corpus in corpora:
        sub = d[d.corpus == corpus].set_index("stage").loc[STAGE_ORDER]
        vals = 1000 * sub["theta_hat"].to_numpy(dtype=float)
        lo = 1000 * sub[lo_col].to_numpy(dtype=float)
        hi = 1000 * sub[hi_col].to_numpy(dtype=float)
        err = np.vstack([vals - lo, hi - vals])
        xpos = x + offsets[corpus]
        significant = (lo > 0) | (hi < 0)
        ax.errorbar(xpos, vals, yerr=err, fmt="none", ecolor=colors[corpus],
                    elinewidth=1.8, capsize=3.5, capthick=1.4, zorder=2)
        ax.scatter(xpos[significant], vals[significant], s=82,
                   marker=markers[corpus], facecolor=colors[corpus],
                   edgecolor="white", linewidth=0.8, zorder=3)
        ax.scatter(xpos[~significant], vals[~significant], s=82,
                   marker=markers[corpus], facecolor="white",
                   edgecolor=colors[corpus], linewidth=1.8, zorder=3)

    ax.axhline(0, color="#333333", linewidth=1.0, zorder=1)
    ax.set_xticks(x)
    ax.set_xticklabels([r"$\theta_1$" + "\nExtraction",
                        r"$\theta_2$" + "\nStat review",
                        r"$\theta_3$" + "\nResearcher DoF",
                        r"$\theta_4$" + "\nTheory/context",
                        r"$\theta_{\mathrm{res}}$" + "\nResidual"])
    ax.set_ylabel(r"Stage contribution ($\hat\theta_m\times10^{-3}$)")
    ax.set_title(f"Cross-fitted stage attribution: {interval_title}", fontsize=12, pad=12)
    ax.grid(axis="y", color="#D9D9D9", linewidth=0.7)
    ax.set_axisbelow(True)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    corpus_handles = [
        Line2D([], [], linestyle="none", marker=markers[c], markersize=8,
               markerfacecolor=colors[c], markeredgecolor="white", label=labels[c])
        for c in corpora
    ]
    corpus_legend = ax.legend(handles=corpus_handles, loc="upper center",
                              bbox_to_anchor=(0.5, -0.15), ncol=3, frameon=False,
                              handletextpad=0.5, columnspacing=1.5)
    ax.add_artist(corpus_legend)
    significance_handles = [
        Line2D([], [], linestyle="none", marker="o", markersize=8,
               markerfacecolor="#555555", markeredgecolor="#555555",
               label="95% CI excludes 0"),
        Line2D([], [], linestyle="none", marker="o", markersize=8,
               markerfacecolor="white", markeredgecolor="#555555",
               markeredgewidth=1.6, label="95% CI includes 0"),
    ]
    ax.legend(handles=significance_handles, loc="upper right", frameon=False,
              fontsize=9, handletextpad=0.5)
    fig.tight_layout(rect=[0, 0.07, 1, 1])
    return fig


def main():
    d = pd.read_csv(os.path.join(HERE, "results", "dml_theta_all.csv"))
    os.makedirs(DOC_DIR, exist_ok=True)
    os.makedirs(FIG_DIR, exist_ok=True)

    tex = build_table(d)
    tex_path = os.path.join(DOC_DIR, "table_dml_theta.tex")
    with open(tex_path, "w") as f:
        f.write(tex + "\n")
    print(f"Wrote {tex_path}")

    figure_specs = [
        ("cluster_robust", "ci95_lo_normal", "ci95_hi_normal",
         "cluster-robust 95% intervals"),
        ("bootstrap", "ci95_lo_boot", "ci95_hi_boot",
         "bootstrap 95% intervals"),
    ]
    for slug, lo_col, hi_col, interval_title in figure_specs:
        fig = build_figure(d, lo_col, hi_col, interval_title)
        fig_path = os.path.join(FIG_DIR, f"dml_theta_attribution_{slug}.pdf")
        fig.savefig(fig_path)
        print(f"Wrote {fig_path}")
        png_path = fig_path.replace(".pdf", ".png")
        fig.savefig(png_path, dpi=150)
        print(f"Wrote {png_path}")
        plt.close(fig)


if __name__ == "__main__":
    main()
